### ISSUE TITLE
Toys, please?

### ISSUE THREAD

**Issue by vcvpaiva** [ontologyportal/sumo#109]
some mappings that could be more specific:
103219362 - doll's_house, dollhouse
103397947 - Frisbee
103523633 - hobby, hobbyhorse, rocking_horse
103548402 - hula-hoop
103590588 - jack-in-the-box
103607756 - kaleidoscope
103621473 - kite
103655295 - Lego, Lego_set
103963813 - playhouse, wendy_house
104399382 - teddy, teddy_bear

**Comment by apease** [comment]
added some concepts to capture types of toys to SUMO and updated the mappings.  See http://sigma.ontologyportal.org:8080/sigma/Graph.jsp?kb=SUMO&lang=EnglishLanguage&flang=SUO-KIF&relation=subclass&term=AnimalDoll&up=4&down=1&limit=&inst=inst&columns=direct-children&columns=documentation&columns=graph&scrWidth=1452&view=text&submit=submit
