### ISSUE TITLE
equivalentContentClass subsumesContentClass contradiction

### ISSUE THREAD

**Issue by fcbr** [ontologyportal/sumo#11]
This one I found using the Sigma translation.  Seems related to the other ones.  If I understood the proof correctly:

```
(instance subsumesContentClass BinaryPredicate)
(instance subsumesContentClass PartialOrderingRelation)
(subrelation equivalentContentClass subsumesContentClass)
```

and:

```
(subclass PartialOrderingRelation AntisymmetricRelation)
```

but:

```
(instance equivalentContentClass EquivalenceRelation)
(subclass EquivalenceRelation SymmetricRelation)
```

Thus `equivalentContentClass` is `SymmetricRelation` and `AntisymmetricRelation`.

**Comment by apease** [comment]
Hi Fabricio,
   Great catch!  It looks like the thing to do is to remove the statement

(subrelation equivalentContentClass subsumesContentClass)

many thanks,
Adam

On 06/02/2016 04:00 AM, Fabricio Chalub wrote:
> This one I found using the Sigma translation. Seems related to the other
> ones. If I understood the proof correctly:
>
> |(instance subsumesContentClass BinaryPredicate) (instance
> subsumesContentClass PartialOrderingRelation) (subrelation
> equivalentContentClass subsumesContentClass) |
>
> and:
>
> |(subclass PartialOrderingRelation AntisymmetricRelation) |
>
> but:
>
> |(instance equivalentContentClass EquivalenceRelation) (subclass
> EquivalenceRelation SymmetricRelation) |
>
> Thus |equivalentContentClass| is |SymmetricRelation| and
> |AntisymmetricRelation|.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ontologyportal/sumo/issues/11>, or mute the thread
> <https://github.com/notifications/unsubscribe/ACBvHQWawHrrvlQJ1FmT7J_4SC62mkTUks5qHre0gaJpZM4IscF6>.
>

-- 
-------------------
Adam Pease
http://www.ontologyportal.org
http://www.articulatesoftware.com
http://www.adampease.org

**Comment by arademaker** [comment]
Are you going to remove or what us to make a PR?

**Comment by apease** [comment]
Hi Alexandre,
   I can remove it.  I thought I'd post first and give myself time to 
double check whether that is the right solution.  I'd also like to 
combine that with a change to another one of these problems that I think 
we discussed previously.
   Many thanks for finding these!

Adam

On 06/02/2016 07:42 AM, Alexandre Rademaker wrote:
> Are you going to remove or what us to make a PR?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/ontologyportal/sumo/issues/11#issuecomment-223313232>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ACBvHY_ShIRKeodC8tMGUAmyWfOwK-xQks5qHuu_gaJpZM4IscF6>.
>

-- 
-------------------
Adam Pease
http://www.ontologyportal.org
http://www.articulatesoftware.com
http://www.adampease.org

**Comment by apease** [comment]
removed subrelation statement, closing issue
