### ISSUE TITLE
Arithmetic in SUO-KIF

### ISSUE THREAD

**Issue by arademaker** [ontologyportal/sumo#12]
ListLengthFn, for instance is defined like:

```
(forall (@ROW ?ITEM)
  (equal
    (ListLengthFn (ListFn @ROW ?ITEM))
    (SuccessorFn (ListLengthFn (ListFn @ROW)))))
```

and SuccessorFn is defined as:

```
(forall (?NUMBER)
  (equal (SuccessorFn ?NUMBER) (AdditionFn ?NUMBER 1)))
```

Where it's Sigma translation is:

```
fof(kb_SUMO_4453,axiom,(
    ! [NUMBER] :
      ( s_instance(NUMBER,s_Integer)
     => s_SuccessorFn(NUMBER) = plus(NUMBER,1) ) )).
```

So AdditionFn was translated to plus, but unless I'm missing
something, plus is not a TPTP-FOF predefined function.

I also don't see any reference to plus in the E documentation.

Looking at the TPTP site, it looks like arithmetic is defined for TFF
and THF only ($sum, etc.)?

**Comment by apease** [comment]
TPTP translation has been updated and we now have a TFF0 translation to address this
