### ISSUE TITLE
Predicates vs Relations

### ISSUE THREAD

**Issue by nordlow** [ontologyportal/sumo#137]
What is the difference between a `Relation` and `Predicate` in SUMO?

I've looked at some examples in `Merge.kif` but cannot get my head around the difference.

Further, is there a section in a Adam Pease's book Ontology that describes this?

Take, for instance,

```
(instance sibling BinaryPredicate)
(instance sibling PartialValuedRelation)
(subrelation sibling familyRelation)
(instance sibling SymmetricRelation)
(instance sibling IrreflexiveRelation)
```

.

Why not instead use

```
(instance sibling BinaryPredicate)
(instance sibling SymmetricPredicate)
```

or even

```
(instance sibling SymmetricBinaryPredicate)
```

?

**Comment by apease** [comment]
Hi Per, you're right, it's just a careless error on my part most likely.  We have 
(partition Relation Predicate Function List) at Merge.kif 2257.  So a Predicate is just a Relation that is not a Function or a List.  That's the case for sibling.  I have a sinking feeling there might be more cases of this careless error too.  Thanks for catching it.

**Comment by apease** [comment]
oh, I responded too quickly I guess, there is no SymmetricPredicate so the statements on sibling are correct.  Because SymmetricRelation covers both predicates and functions it is named accurately

**Comment by nordlow** [comment]
So you can view a relation as super-concept of a predicate or function, then?

**Comment by apease** [comment]
Yes, that's in part what the statement (partition Relation Predicate Function List)	says.

**Comment by apease** [comment]
addressed questions, no action item, closing issue
