### ISSUE TITLE
contradiction found in disjointDecomposition

### ISSUE THREAD

**Issue by fcbr** [ontologyportal/sumo#14]
We were trying to reproduce the "banana slug" experiment in:

Pease, A., Sutcliffe, G., Siegel, N., and Trac, S., (2010). _Large Theory Reasoning with SUMO at CASC_, AI Communications, Volume 23, Number 2-3 / 2010, Special issue on Practical Aspects of Automated Reasoning, IOS Press, ISSN 0921-7126, pp 137-144.

Since we have issues with using arithmetic in SUMO (see issue #12), we decided to rewrite the axioms related to `partition`.

We found an issue with `disjoinDecomposition` as follows.  The original was:

```
(=>
   (disjointDecomposition ?CLASS @ROW)
   (forall (?ITEM1 ?ITEM2)
      (=>
         (and
            (inList ?ITEM1 (ListFn @ROW))
            (inList ?ITEM2 (ListFn @ROW))
            (not
               (equal ?ITEM1 ?ITEM2)))
         (disjoint ?ITEM1 ?ITEM2))))
```

There was already another axiom, as follows:

```
(<=>
  (disjointDecomposition ?CLASS ?ROW1 ?ROW2 ?ROW3)
  (and
    (disjoint ?ROW1 ?ROW2)
    (disjoint ?ROW2 ?ROW3)
    (disjoint ?ROW3 ?ROW1)))
```

We added a new one for the case of only two row items as follows:

```
(<=>
  (disjointDecomposition ?CLASS ?ROW1 ?ROW2)
  (disjoint ?ROW1 ?ROW2))
```

From the axiom above and given that:

```
(disjoint CorpuscularObject Substance)
```

we were able to prove:

```
(disjointDecomposition Substance CorpuscularObject Substance)
```

From that, it follows:

```
(subclass CorpuscularObject Substance)
(subclass Substance Substance)
```

Given that `BananaSlug10-1` is an instance of `CorpuscularObject` (since it is an `Animal`, etc.) it follows that `BananaSlug10-1` is an instance of `Substance`, which contradicts the `disjoint` statement above.

We suggest to change the equivalence to an implication as follows:

```
(=>
  (disjointDecomposition ?CLASS ?ROW1 ?ROW2 ?ROW3)
  (and
    (disjoint ?ROW1 ?ROW2)
    (disjoint ?ROW2 ?ROW3)
    (disjoint ?ROW3 ?ROW1)))

(=>
  (disjointDecomposition ?CLASS ?ROW1 ?ROW2)
  (disjoint ?ROW1 ?ROW2))
```

(EDIT: fixing typos)

**Comment by fcbr** [comment]
Update: after rerunning our "banana slug" experiment with the changes proposed above, we were able to find a _real_ proof of banana slug being an invertebrate.

**Comment by arademaker** [comment]
By /real/ proof @fcbr means a proof that 'banana slug' is an invertebrate that is not by /contradiction/ based on the fact that from an inconsistent ontology one can derive anything.

**Comment by vcvpaiva** [comment]
is this issue to be closed or not? 

do the proposed modifications have been checked and implemented?

**Comment by apease** [comment]
This axiom is in error

(<=>
  (disjointDecomposition ?CLASS ?ROW1 ?ROW2 ?ROW3)
  (and
    (disjoint ?ROW1 ?ROW2)
    (disjoint ?ROW2 ?ROW3)
    (disjoint ?ROW3 ?ROW1)))

it should just be a forward implication.  So the axiom that Fabricio introduced following this pattern is also faulty and the root of the contradiction.  I'll fix the original axiom

**Comment by fcbr** [comment]
yes that was our suggestion:

> We suggest to change the equivalence to an implication as follows:

**Comment by apease** [comment]
very grateful for all your help on finding these bugs!
