### ISSUE TITLE
minValue

### ISSUE THREAD

**Issue by arademaker** [ontologyportal/sumo#160]
The minValue is defined in the Merge.kif but never used.  Even if it makes sense to keep this definition, the standard approach to produce tf0 or fof files will produce many axioms from the 

```
(documentation minValue EnglishLanguage "The minimum possible value for a given
numerical argument of a &%Relation. The second argument is the argument number
of the relation and the third argument is the minimum value.")
(domain minValue 1 Relation)
(domain minValue 2 Integer)
(domain minValue 3 Quantity)

(=>
  (and
    (minValue ?R ?ARG ?N)
    (?R @ARGS)
    (equal ?VAL (ListOrderFn (ListFn @ARGS) ?ARG)))
  (greaterThan ?VAL ?N))
```

given that minValue must be defined for all relations in the ontology. On the other hands, maybe it could be a good idea to introduce the notion of `lazy generation` of axioms in the transformations. That would be an issue for the https://github.com/ontologyportal/sigmakee repository.

**Comment by apease** [comment]
Lazy generation is possible, but I don't think would address any performance bottlenecks at the moment.  We could try to find a way to constrain the types for this axiom since it only applies to relations that have a numerical argument

**Comment by fcbr** [comment]
On a more practical note, options such as this (from `E`) should prove useful:

```
  --sine[=<arg>]
    Apply SInE to prune the unprocessed axioms with the specified filter.
    'Auto' will automatically pick a filter. The option without the optional
    argument is equivalent to --sine=Auto.
```

> E currently implements two types of filters. The major filter type is a configurable variant of Krystoff Hoder’s SInE algorithm [HV11] for pruning large specification. The basic idea of this filter is to rate function- and predicate symbols by their rarity - the less often a symbol occurs in the specification, the more important any given formula or clause that handles the symbol is for the definition of that symbol. The algorithm starts by computing the D-relation between clauses/formulas and symbols. A clause/formula is in the D-relation with the rarest symbols that occur in it. The exact details of ”rarest” are configurable in a number of ways - see below.

```
[HV11] Hoder, Krystof & Voronkov, Andrei. (2011). Sine Qua Non for Large Theory 
       Reasoning. 299-314. 10.1007/978-3-642-22438-6_23.
```

**Comment by arademaker** [comment]
yes, we can delegate the problem to the provers, but surely it would be good to deal with that in the transformation too.

**Comment by apease** [comment]
Hoder's algorithm was a key advance in large theory proving.  I also implemented it in Sigma in com.articulate.sigma.SInE .  But since Vampire and E both implemented it I don't use that Java code very often.

**Comment by arademaker** [comment]
So I will close this issue. No action item here, right? The issue https://github.com/ontologyportal/sigmakee/issues/38 is the only real problem to solve here. Please reopen if you disagree.
