### ISSUE TITLE
how to determine the class of the arguments of instances of VariableArityRelations?

### ISSUE THREAD

**Issue by arademaker** [ontologyportal/sumo#162]
```
(domainSubclass exhaustiveAttribute 1 Attribute)
(domain exhaustiveAttribute 2 Attribute)
(documentation exhaustiveAttribute EnglishLanguage "This predicate relates a &%Class to a
set of &%Attributes, and it means that the elements of this set exhaust the
instances of the &%Class.  For example, (&%exhaustiveAttribute &%PhysicalState
&%Solid &%Fluid &%Liquid &%Gas &%Plasma) means that there are only five instances of
the class &%PhysicalState, viz. &%Solid, &%Fluid, &%Liquid, &%Gas and &%Plasma.")

(=>
   (exhaustiveAttribute ?CLASS @ROW)
   (=>
      (inList ?ATTR (ListFn @ROW))
      (instance ?ATTR Attribute)))
```

Above, `exhaustiveAttribute` should receive `SetOrClass` not `Attribute`, right?  Moreover, how to declare that **all** arguments should be of type `SetOrClass`? Above, only the second argument was determined as being `Attribute`, what about the others? Is this an implicit definition of minimum arity?

**Comment by apease** [comment]
The first argument to exhaustiveAttribute is a class, per the domainSubclass statement.  The other arguments are instances of Attribute.  For example 

(exhaustiveAttribute AnimacyAttribute Living Dead)

Use of the row variable, as designated with'@' means there are one or more arguments that can be used in place of the row variable.  All must have the same type

**Comment by whitten** [comment]
I'm not sure that it should say (inList ?ATTR (ListFn @ROW)
as I think of this as a set.

If you had (exhaustiveAttribute AnimacyAttribute Living Dead Living Dead)
it shouldn't mean anything more than (exhaustiveAttribute AnimacyAttribute Living Dead)

Arademaker, the relation (inList ?ATTR (ListFn @ROW)) can be read as
If you made a List from all the arguments in @ROW and then checked each of the elements in that list,  binding each element in turn to the variable ?ATTR, then that element is an instance of Attribute.

I'm comfortable with @ROW having more than one value, but isn't there a degenerate case where @ROW is empty that should be addressed?

**Comment by apease** [comment]
Lists are ordered and sets are unordered.  A list is set but a set is not a list.

`(exhaustiveAttribute AnimacyAttribute Living Dead Living Dead)`
does indeed mean the same thing as `(exhaustiveAttribute AnimacyAttribute Living Dead) `although we should add an axiom that requires each argument to be distinct so as to prohibit this pathological case

```
(=>
   (exhaustiveAttribute ?CLASS @ROW)
   (=>
      (equal ?ATTR1 (ListOrderFn ?N1 (ListFn @ROW)))
      (not
        (exists (?ATTR2 ?N2)
            (and
              (equal ?ATTR1 ?ATTR2)
              (not
                 (equal ?N1 ?N2)))))))
```

row variables must have one or more variables per the syntax of SUO-KIF an its implementation in Sigma.

**Comment by apease** [comment]
this axiom might be expanded to any VariableArity Relation.  If anyone thinks of one where it doesn't apply, please let me know....

**Comment by apease** [comment]
aha, ListFn is one, so much for generalization this time...

**Comment by whitten** [comment]
Hmm a list is a set?  I'm not sure I think this is true. 
Doesn't a set also guarantee the elements are distinct ?
If not, I would think it would be an axiom on the set definition.
I thought adding an element to a set which was already in the set won't change the set. (ie: it is an idempotent operation)
sigma supports your statement though: 115312015 "A &%SetOrClass that satisfies extensionality as well as other constraints specified by some choice of set theory. &%Sets differ from &%Classes in two important respects. First, &%Sets are extensional - two &%Sets with the same &%elements are identical. Second, a &%Set can be an arbitrary stock of objects. That is, there is no requirement that &%Sets have an associated condition that determines their membership. Note that &%Sets are not assumed to be unique sets, i.e. &%elements of a &%Set may occur more than once in the &%Set." (entry from SUMO termFormat and documentation) .

I don't see any axiomizing of the concepts in this paragraph comment. The OWL version just has the comment.

Is there a SUMO term for the idea I was thinking about, corresponding to the phrase "unique set" in the paragraph above ? I looked up "unique set" but no glory.

I hadn't though about sets not having an order, as I assumed you could iterate over all of the elements in it. Is that actually axiomatized ?

**Comment by whitten** [comment]
Adam said : aha, ListFn is one, so much for generalization this time...
In my opinion,  It is a good relation to have, and worthy of a name ad used in defining a subset of the VariableArityRelation where it holds.

**Comment by apease** [comment]
sorry, I wrote too quickly and of course you are right.  Lists can have duplicates so a list can be (but is not necessarily) a set.  A set however can't be a list because it is necessarily unordered (therefore one can iterate over it, as one can in Java, but the order is not guaranteed). Adding an element to a set which is already in the set doesn't change the set.  The OWL version of SUMO is not authoritative since it necessarily omits all the axioms that aren't expressible in OWL (i.e. most of them)

**Comment by whitten** [comment]
I recognized that the OWL format wasn't the end-all definition. I have been told that OWL when unspecified should be read as OWL-DL, but I've been told that OWL-FULL has much better expressive power.  What is your experience with OWL-FULL or is it not really standardized enough to use?

I seem to recall a Bag is like a set, as it doesn't have ordering, but does allow a count of how many times an element is in the Bag.  Is that a useful concept here?

**Comment by whitten** [comment]
as to your "distinct argument predicate" :
(=>
   (exhaustiveAttribute ?CLASS @ROW)
   (=>
      (equal ?ATTR1 (ListOrderFn ?N1 (ListFn @ROW)))
      (not
        (exists (?ATTR2 ?N2)
            (and
              (equal ?ATTR1 ?ATTR2)
              (not
                 (equal ?N1 ?N2)))))))

what would change if you used a Variadic predicate that is true when all of its arguments are different ? (I looked for DifferentFn but did not find it)

**Comment by apease** [comment]
OWL-full has slightly greater expressive power than OWL-DL, but still much less than first order logic.  It's standardized but of insufficient expressive power to accomplish what I think ontologies are for - to capture definitions of most concepts in a computable logic form.

Bags are unordered but may contain duplicates

**Comment by apease** [comment]
There is no DifferentFn but you could define one....

**Comment by arademaker** [comment]
First answer, our mistake! A bug! Maybe @fcbr can remember more details ...

**Comment by fcbr** [comment]
>  can remember more details

sorry, more details about what exactly? ;-)

**Comment by arademaker** [comment]
@apease, sorry, I may be missing something. My understanding is that the axiom `(domainSubclass exhaustiveAttribute 1 Attribute)` says that the first argument of `exhaustiveAttribute` is subclass of `Attribute`, we can say that `Attribute` is an instance of `SetOrClass` but not a subclass of `SetOrClass`. Am I right?

The fact that `Attribute` is an instance of `SetOrClass` is explored in the documentation string of `exhaustiveAttribute` below, in this [axiom](https://github.com/ontologyportal/sumo/blob/master/Merge.kif#L560-L568) and also by the definition of the `instance` predicate (as we have discussed not long ago).

> For example, (&%exhaustiveAttribute &%PhysicalState &%Solid &%Fluid &%Liquid &%Gas &%Plasma) means that there are only five instances of the class &%PhysicalState, viz. &%Solid, &%Fluid, &%Liquid, &%Gas and &%Plasma.

But what is new for me, and I believe not properly documented anywhere, is that in the case of `(exhaustiveAttribute AnimacyAttribute Living Dead)` and `(domain exhaustiveAttribute 2 Attribute)` we should undertand that arguments in the thrid and forty position should have the same type, in this case, `Attribute`. That is, nothing is said about how to compute the types of the arguments of `VariableArityRelation` relations. Moreover, SUO-KIF specification is also not very liberal regarding the position of row variables, saying nothing about it. On the other hand,  Hayes and Menzel says:

> An SKIF sentence is in schema form if row variables are (1) restricted to universal quantifiers at the top level of any assertion (i.e., not within the scope of any expression other than a universal quantifier), and (2) only occur in the final position of any atomic sentence or relational term and (3) if the sentence is used only as an assertion, and never posed as a theorem to be proved.

P. Hayes and C. Menzel, “A Semantics for the Knowledge Interchange Format,” May 2001.

I didn't understand your comment [above](https://github.com/ontologyportal/sumo/issues/162#issuecomment-502314411):

> row variables must have one or more variables per the syntax of SUO-KIF an its implementation in Sigma.

I have failled to see what is the pathological case you are trying to avoid with the proposed axiom. But I imagine other axioms using row variables would have similar problem, right?

**Comment by apease** [comment]
The pathological case is the one Fabricio mentioned above:
(exhaustiveAttribute AnimacyAttribute Living Dead Living Dead)

**Comment by apease** [comment]
added axiom above to prevent the pathological case

**Comment by arademaker** [comment]
Sorry, I didn't understand yet the pathological case! Are we talking about the empty list? Or the repetition in the list? In the second case, what is the problem with repetitions?

You said Fabricio but I am assuming you want to say @whitten, right?

**Comment by apease** [comment]
sorry to @whitten and @fcbr I confused your posts 
@arademaker it's the second case :  (exhaustiveAttribute AnimacyAttribute Living Dead Living Dead) .  I guess one might say that causes no harm, but it's better not to allow it
