### ISSUE TITLE
altitude distance contradiction

### ISSUE THREAD

**Issue by fcbr** [ontologyportal/sumo#17]
Similar to #7 and others, so I'll skip the details:

```
(subrelation altitude distance)
(instance altitude PartialValuedRelation)
(instance distance TotalValuedRelation)
```

**Comment by apease** [comment]
substituted

(=>
  (altitude ?OBJ1 ?OBJ2 ?Q)
  (distance ?OBJ1 ?OBJ2 ?Q))

for the subrelation statement
