### ISSUE TITLE
mother/father parent contradiction

### ISSUE THREAD

**Issue by fcbr** [ontologyportal/sumo#18]
Similar to others, so I'll skip the details:

```
(subrelation mother parent)
(subrelation father parent)
(instance mother PartialValuedRelation)
(instance parent TotalValuedRelation)
```

**Comment by apease** [comment]
Hi Fabricio,
   Many thanks for all the bug reports.  I'll take a look and try to 
fix, although it might be a couple of days.

Adam

On 06/15/2016 11:55 AM, Fabricio Chalub wrote:
> Similar to others, so I'll skip the details:
>
> |(subrelation mother parent) (subrelation father parent) (instance mother
> PartialValuedRelation) (instance parent TotalValuedRelation) |
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ontologyportal/sumo/issues/18>, or mute the thread
> <https://github.com/notifications/unsubscribe/ACBvHbZ4wJGZ9LinhyllJzppW6M3CoHCks5qMEqIgaJpZM4I2rao>.
>

-- 
-------------------
Adam Pease
http://www.ontologyportal.org
http://www.articulatesoftware.com
http://www.adampease.org

**Comment by apease** [comment]
substituted

(=>
  (mother ?A ?B)
  (parent ?A ?B))

for the subrelation statement (for father too)
