### ISSUE TITLE
subclass axiom 

### ISSUE THREAD

**Issue by arademaker** [ontologyportal/sumo#181]
In Merge.kif:

```
(instance subclass BinaryPredicate)
(instance subclass PartialOrderingRelation)
(domain subclass 1 SetOrClass)
(domain subclass 2 SetOrClass)

...

(=>
  (subclass ?X ?Y)
  (and
    (instance ?X SetOrClass)
    (instance ?Y SetOrClass)))
```

During FOL transformation, the domain declarations are used to create the restriction to the axiom but the axiom itself is being defined to properly type the arguments.  So the axiom can be irrelevant or there is more on the 'operational semantics' of the implicit type system of SUMO to consider.

**Comment by apease** [comment]
yes, this axiom is redundant (although harmless)

**Comment by arademaker** [comment]
and useless! It produced a FOL tautology `α → β → α`

**Comment by nordlow** [comment]
Further, isn't also

```
(=>
  (and
    (subclass ?X ?Y)
    (instance ?Z ?X))
  (instance ?Z ?Y))
```

redundant

with 

```
(instance subclass PartialOrderingRelation)
```

?

**Comment by arademaker** [comment]
@nordlow can you open a new issue about this question about PartialOrderingRelation and the redundancy you are questioning ...

**Comment by arademaker** [comment]
@nordlow here my opinion:

PartialOrderingRelation does have its semantics defined by the axioms about Reflexive, TotalValue and Transitive. 

But this is different of defining what does it means subclass. Say that subclass is PartialOrderingRelation , only says how subclass propagate in the hierarchy of classes.

**Comment by arademaker** [comment]
Considering that I answered the question. We can close it, issue #190 further discuss the problem that opened this issue
