### ISSUE TITLE
Why aren't all Role instances subclasses?

### ISSUE THREAD

**Issue by nordlow** [ontologyportal/sumo#182]
Why is the SUMO term `Scientist` an `instance` of `Profession` instead of a `subclass`? There are obviously many different kinds of scientists such as SUMOs `Physicist`.

So why not instead express this as

```
(subclass Scientist Profession)
(subclass Physicist Scientist)
```

make every occupation type potentially have a (yet unnamed) subclass?

This would more naturally map with ontologies such as DBpedia's OWL ontology and ease its alignment with SUMO representation of roles. This provided that we exclude the DBpedia-subclass relation between SUMO `Person` and `Occupation`.

**Comment by apease** [comment]
SUMO's professions are attributes that are related to instances of Human, professions can change over the lifetime of the Human.  The &%attribute relation is between an instance of Human and an instance of Attribute.  So in (attribute Human234 Scientist) both Human234 and Scientist are instances.  We use the subAttribute relation to specify more detailed attributes. So we have (subAttribute Physicist Scientist) http://sigma.ontologyportal.org:8080/sigma/Browse.jsp?kb=SUMO&lang=EnglishLanguage&flang=SUO-KIF&term=Scientist

**Comment by nordlow** [comment]
Thanks.
