### ISSUE TITLE
Representing OWL's equivalence predicates

### ISSUE THREAD

**Issue by nordlow** [ontologyportal/sumo#187]
How can `owl:equivalentClass` [1], `owl:equivalentProperty` [2] and `owl:sameAs` [3] be represented using SUMO predicates?

[1] www.w3.org/2002/07/owl#equivalentClass
[2] https://www.w3.org/TR/owl-ref/#equivalentProperty-def
[3] https://www.w3.org/TR/owl-ref/#sameAs-def

**Comment by apease** [comment]
If one term is in SUMO and another is external, then use synonymousExternalConcept whether it's a class or a relation.  This correspondence is also handled automatically in the Sigma OWLtranslator.java class

**Comment by nordlow** [comment]
Thanks!

**Comment by nordlow** [comment]
I still think there is room for a SUMO-equivalent binary/nary predicate of OWL's `sameAs`.

What would its associated axioms look like?

**Comment by apease** [comment]
SUMO already has synonymousExternalConcept to fulfill that need

**Comment by nordlow** [comment]
Ok, thanks.

BTW, how is one to interpret

```
(relatedInternalConcept relatedExternalConcept relatedInternalConcept)
```

?

**Comment by apease** [comment]
These indicate that the concepts are "related" but not equivalent and the axiom(s) specifying the details of the relationship have not (yet) been created). Statement of this sort are a great opportunity to encode a new axiom.  For example, (relatedInternalConcept CarbonDioxideEmission VehicularPollution).

**Comment by apease** [comment]
oh, you're asking about this statement specifically.  It says that the notion of a concept external to SUMO being 'related' to an 'internal' concept is also 'related' to the notion of two concepts in SUMO being 'related'

**Comment by arademaker** [comment]
Sorry, I was curious about the predicate `synonymousExternalConcept`. I found many uses of this predicate in the Military.kif:

```lisp
(synonymousExternalConcept "2nd Lieutenant" USMilitaryRankO1 USMarineCorpsRankingSystem)
(synonymousExternalConcept "Three Star General" USMilitaryRankO9 USArmyRankingSystem)
```

but also

```lisp
(synonymousExternalConcept "main telephone line" MainTelephoneLine EnglishLanguage)
```

But the documentation of this predicate says

> (synonymousExternalConcept ?STRING ?THING ?LANGUAGE) means that the SUMO concept THING has the same meaning as STRING in LANGUAGE.

But some of the above cases could also be encoded with the `termFormat` predicate, right? Maybe this question is also related to my confusion with Language vs ontology. This issue started with the discussion about how to connect SUMO concepts with concepts in another ontology, right? But `synonymousExternalConcept` is about concepts and their representation as strings in Languages.

**Comment by apease** [comment]
The latter example is incorrect and should use termFormat

**Comment by apease** [comment]
fixed in https://github.com/ontologyportal/sumo/commit/b2b3143e5d11ebeab3bb80f27f03ef4559d5788e
