### ISSUE TITLE
Inconsistency generated by type restrictions and relativization before and earlier

### ISSUE THREAD

**Issue by fcbr** [ontologyportal/sumo#20]
EDIT: the inconsistency is between `before` and `earlier` and not `holdsPosition`.  I have edited the description below:

Unlike the others, this is not related to `subrelation`.

We found an issue that seemed to be related to our relativization, but it may be actually related to the way SUMO specifies the types for `before` and `earlier`.

```
(partition TimePosition TimeInterval TimePoint)
(domain holdsDuring 1 TimePosition)
(domain before 1 TimePoint)
(domain earlier 1 TimeInterval)
```

Given these domain specifications, we have the following axiom:

```
(=>
   (and
      (instance ?PREDICT Predicting)
      (patient ?PREDICT ?FORMULA))
   (exists (?TIME)
      (and
         (holdsDuring ?TIME ?FORMULA)
         (or
            (before ?TIME (WhenFn ?PREDICT))
            (earlier ?TIME (WhenFn ?PREDICT))))))
```

Notice that, due to the usage of `?TIME` in both and `before` and `earlier`, we end up with a relativization like this one (output from Sigma, reformatted with `tptp4X` for clarity):

```
fof(kb_SUMO_663,axiom,(
    ! [V__FORMULA,V__PREDICT] :
      ( s__instance(V__FORMULA,s__Formula)
     => ( ( s__instance(V__PREDICT,s__Predicting)
          & s__patient(V__PREDICT,V__FORMULA) )
       => ? [V__TIME] :
            ( s__instance(V__TIME,s__TimeInterval)
            & s__instance(V__TIME,s__TimePoint)
            & s__holdsDuring(V__TIME,V__FORMULA)
            & ( s__before(V__TIME,s__WhenFn(V__PREDICT))
              | s__earlier(V__TIME,s__WhenFn(V__PREDICT)) ) ) ) ) )).
```

Notice the requirement that `V__TIME` be a `s__TimeInterval` and `s__TimePoint`, which is forbidden by the `partition` statement above.

The full proof is way more complicated than this explanation and frankly I haven't been able to follow it completely.  The explanation in this issue is what I have been able to gather by looking at the axioms and the TPTP translation.  I can provide the full proof if required.

While this seems an issue with Sigma and relativization, it can also be thought as an issue with SUMO, since its type requirements for `before` and `earlier` are incompatible.

**Comment by apease** [comment]
changed the axiom in question just to be concerned with intervals
