### ISSUE TITLE
Skolemization of SUMO axioms

### ISSUE THREAD

**Issue by nordlow** [ontologyportal/sumo#202]
After having read part 3 of

https://en.wikipedia.org/wiki/Conjunctive_normal_form#Converting_from_first-order_logic

I wonder about the practical meaning of the word "scope" in the expression

"The general rule is that the universal quantifiers  determine Skolem function arguments. There must be one argument for each universal quantifiable variable whose _scope_ contains the existentially quantified variable that the Skolem function replaces."

taken from the book Artificial Intelligence by Patrick Henry Winston.

Specifically, in which cases will a Skolem function depend on a strict subset of all the universally quantified variables used in an axiom? In other words, if we move all quantifiers upwards through all conjunctions, disjunctions and negations I can't imagine a case where each Skolem function `f` will depend on a scope other than the whole scope of the axiom that contain `f`.

**Comment by arademaker** [comment]
I am not sure if I understood your question. Scope in KIF is unambiguous defined given the prefix notation 

(forall (?X)...)

In the dots above, the variable ?X is considered bounded. It is the scope where ?X exists.

Talking about skolemization, consider the case where we have

(forall (?X) ... (exists (?Y) .... (forall (?Z) ...)

When we skolemize Y we have to replace it by a function depend on X. But Y does not depending on Z. So not all universally quantified variable in the axiom will participate on the skolemization of an existentially quantified variable.

The point is that skolemization is defined independent of other transformations such as the prefixation of all quantifiers.

**Comment by arademaker** [comment]
the independent definition make sense. You can of course avoid entirely skolemization if you choose to rewrite all forall by exists

But them , you have to deal with https://github.com/ontologyportal/sumo/issues/201#issuecomment-568220611

**Comment by nordlow** [comment]
> the independent definition make sense. You can of course avoid entirely skolemization if you choose to rewrite all forall by exists

Don't you mean the opposite: rewriting all `exists` using `forall`?

**Comment by arademaker** [comment]
Yes, transform the exists to forall

**Comment by nordlow** [comment]
> Yes, transform the exists to forall

Use the method I discribed?

**Comment by nordlow** [comment]
> I am not sure if I understood your question. Scope in KIF is unambiguous defined given the prefix notation
> 
> (forall (?X)...)
> 
> In the dots above, the variable ?X is considered bounded. It is the scope where ?X exists.

Clarification, how is the of scope implicitly defined universal variables defined?

**Comment by apease** [comment]
the scope of an implicitly universally quantified variable is the outermost scope - the whole axiom

**Comment by apease** [comment]
@nordlow https://en.wikipedia.org/wiki/Conjunctive_normal_form is also a good resource for explaining skolemization in context.  We based the canonicalization in Sigma on the process outlines in Norvig's AI textbook.  It's implemented in Sigma in the class com.articulate.sigma.Clausifer .  The main method of the class shows the outline of the process https://github.com/ontologyportal/sigmakee/blob/master/src/java/com/articulate/sigma/Clausifier.java line 1846

**Comment by nordlow** [comment]
> the scope of an implicitly universally quantified variable is the outermost scope - the whole axiom

Is this always intentional for all axioms that make use of implicitly universally quantified variables?

**Comment by nordlow** [comment]
BTW, could SUMO provide a function ConjunctiveNormalFormFn that operates on SUMO formulas?

**Comment by apease** [comment]
yes, outermost scope is the result.  If a more limited scope is required then one must have an explicit universal quantifer.  Clausifer does (mostly) what you expect

It has -
    public Formula clausify() 

but you'd initialize it with it's constructor

    public Clausifier(String s) {

which takes the String representation of a Formula, so you could say

Formula myForm = new Formula("(instance Foo Object)");
Clausifier c = new Clausifier(myForm.getFormula());
Formula cnf = c.clausify();

**Comment by nordlow** [comment]
Thanks for all input. I'm closing this for now.
