### ISSUE TITLE
Duplicate definition of class ComputerFile

### ISSUE THREAD

**Issue by nordlow** [ontologyportal/sumo#204]
The class `ComputerFile` is defined twice in both `engineering.kif` as

```
(subclass ComputerFile ContentBearingObject)
```

and in `QoSontology.kif` as

```
(subclass ComputerFile DigitalData)
```

.

Is this intentional?

**Comment by apease** [comment]
it's a bug.  I'll fix shortly.  Many thanks!

**Comment by apease** [comment]
fixed in commit https://github.com/ontologyportal/sumo/commit/8655aefe8d9c146ea65f24a44456646484401ec1
