### ISSUE TITLE
Redefining VocalCords in terms of VocalCord

### ISSUE THREAD

**Issue by nordlow** [ontologyportal/sumo#211]
I suggest changing the definition of `VocalCords` via a new `VocalCord` defined as

```
(subclass VocalCord Organ)
(documentation VocalCord EnglishLanguage "A &%VocalCord is a
mucous membrane stretched horizontally across the larynx. They
vibrate, modulating the flow of air being expelled from the lungs
during &%Vocalizing. ")

(=>
  (instance ?VOCAL Vocalizing)
  (exists (?CORD1 ?CORD2 ?ORGANISM)
    (and
      (instance ?CORD1 VocalCord)
      (instance ?CORD2 VocalCord)
      (instrument ?VOCAL ?CORD1)
      (instrument ?VOCAL ?CORD2)
      (not (equal ?CORD1 ?CORD2))
      (part ?CORD1 ?ORGANISM)
      (part ?CORD2 ?ORGANISM)
      (instance ?ORGANISM Organism))))
```

and then define `VocalChord`s as previously

```
(typicalPart VocalCords Human)
(typicallyContainsPart VocalCords Human)
(initialPart VocalCords Human)
```

together with an axiom for `VocalCords` defining it as a pair of `VocalCord`s. What should that axiom look like?

I presume `Lung`, `Arm`, `Leg` etc should undego the same refactoring/extension.

For more compact encoding it might be useful to define a set of variants of typicalPart and typicallyContainsPart and initialPart that expresses the number of initial parts, in this case two `Lung`s, `VocalCord`s, etc.

**Comment by apease** [comment]
Leg, Arm and Lung are already singular, although it looks like we don't have an axiom to say that people typically have two of each.  Would you like to try writing the axioms for that?  For VocalCords they only work in pairs so I think we should keep the term as is and define VocalCord as a typicalPart.  Would you like to try that alternate version?

**Comment by ArtificialMarty** [comment]
Just a quick nit: in the documentation string for VocalCord, there should
be no comma after "The vocal cords".

I can't help it: Mom was an English teacher....

Marty

**Comment by apease** [comment]
thanks @ArtificialMarty - the fix will appear next time I pushed more substantial updates to git

**Comment by apease** [comment]
added notion of VocalFolds and axioms stating that healthy organisms have pairs of several things.  A more complete inventory of these things is needed
