### ISSUE TITLE
Mismatched arity on calls

### ISSUE THREAD

**Issue by nordlow** [ontologyportal/sumo#213]
Here's all the calls to predicates that has a mismatched arity with the definition of the predicate:

```
/home/per/Work/sumo/mappings/HotelDetail.kif:739:5: warning: `productPrice` takes exactly 3 arguments, 2 were given
/home/per/Work/sumo/development/Biography.kif:214:7: warning: `weddingdate` takes exactly 3 arguments, 2 were given
/home/per/Work/sumo/development/Biography.kif:214:7: warning: `weddingdate` takes exactly 3 arguments, 2 were given
/home/per/Work/sumo/development/Biography.kif:214:7: warning: `weddingdate` takes exactly 3 arguments, 2 were given

**Comment by apease** [comment]
depth actually takes three arguments, could you double check your analysis code?

**Comment by nordlow** [comment]
I'd incorrectly made `depth` a `BinaryPredicate`. Fix is [here](https://github.com/ontologyportal/sumo/pull/214).

**Comment by apease** [comment]
please use Biography.kif in the main, rather than development directory.  It's correct.  But I've fixed it in the development directory as well.  thanks for the report
