### ISSUE TITLE
during temporalPart contradiction

### ISSUE THREAD

**Issue by fcbr** [ontologyportal/sumo#22]
Related to #7 and others, so skipping details:

```
(subrelation during temporalPart)
(instance during IrreflexiveRelation)
(instance temporalPart PartialOrderingRelation)
(subclass PartialOrderingRelation ReflexiveRelation)
```

**Comment by whitten** [comment]
Does SUMO have a hard difference between a relation being an instance of the class of IrreflexiveRelation and a relation being an instance of a class that is a subclass of ReflexiveRelation ?

I agree this looks like a contradiction.

**Comment by fcbr** [comment]
There's no difference: due to [this](https://github.com/ontologyportal/sumo/blob/master/Merge.kif#L142) we can infer that `temporalPart` is a `ReflexiveRelation`.

**Comment by apease** [comment]
changed during to entail that there's a temporalPart rather than being a subrelation of temporalPart
