### ISSUE TITLE
Implicitly quantified variable and existentially quantified variable of the same name

### ISSUE THREAD

**Issue by Regermeister** [ontologyportal/sumo#259]
In Mid-level-ontology.kif, line 11054ff, it says:
```lisp
(=>
  (and
    (instance ?VO VitalOrgan)
    (not
      (part ?VO ?H)))
  (not
    (exists (?H)
      (and
        (instance ?H Animal)
        (attribute ?H Living)))))
```
?H is existentially quantified, but ?H also appears before that.

SigmaKEE's makeQuantifiersExplicit implementation leads me to believe this is a bug, sorry if I'm mistaken

**Comment by Regermeister** [comment]
I tried using that method at some point but it gives me a NullPointerException in SUMOtoTFAform.java in line 1424 (`if (kb.kbCache.checkDisjoint(kb, c1, c2)) {`). I thought w/e and stopped using it cause I don't need it that badly but I just had another look at it.

Apparently kb is null, even though I use it earlier in my program.

I guess SUMOtoTFAform.java doesn't use the kb that is given to isValidFormula, but it should still be the same one? My program calls 

```lisp
KBmanager.getMgr.initializeOnce()
kb = KBmanager.getMgr.getKB("SUMO")
```

SUMOtoTFAform calls

```lisp
KBmanager.getMgr().initializeOnce();
String kbName = KBmanager.getMgr().getPref("sumokbname");
kb = KBmanager.getMgr().getKB(kbName);
```

Actually now that I look at it I'm not sure SUMOtoTFAform ever runs that piece of code. But I dunno. I can open an issue on the SigmaKEE GitHub if you want.

**Comment by apease** [comment]
If you run SUMOjEdit it takes care of initializations for you.  Another thing to try is running KButilities at the command line with the -v option and a quoted formula to test.  It calls SUMOtoTFAform.initOnce(); first

**Comment by Regermeister** [comment]
Thanks!
