### ISSUE TITLE
Function applications as conjuncts?

### ISSUE THREAD

**Issue by Regermeister** [ontologyportal/sumo#263]
I stumbled onto these two formulae in UXExperimentalTerms.kif that look a bit wrong to me:

Line 3441:
```lisp
(=>
  (and
    (ABPFn ?BUYINGS)
    (member ?BUYING ?BUYINGS))
  (instance ?BUYING Buying))
```
Line 3484:
```lisp
(=>
  (and
    (ASPFn ?SELLINGS)
    (member ?SELLING ?SELLINGS))
  (instance ?SELLING Selling))
```

In both of these, a function application is used as a conjunct in a conjunction, which is technically allowed but doesn't really seem to convey a sensible meaning?

Sorry if this is intentional and I'm just not getting it

**Comment by Regermeister** [comment]
Sorry, but I'm not really confident enough in my understanding of the related concepts

In fact I'm not sure why the members of the collection would be instances of Buying/Selling rather than just the actual things that are being bought/sold (so a patient of an instance of Buying/Selling rather than the Buying/Selling instance itself)

**Comment by apease** [comment]
Things only have a price when offered or sold.  Any thing doesn't inherently have a price for all time. The same thing (like a famous painting) could be bought and sold many times for different prices.  So, one can only state that a thing has a price in the context of a given transaction (or offer).

**Comment by apease** [comment]
just pushed a fix, many thanks for pointing out the problem, and let me know if at some point you have time and interest in learning how to write SUMO statements
