### ISSUE TITLE
all parents must be older than their Childs? 

### ISSUE THREAD

**Issue by arademaker** [ontologyportal/sumo#274]
I found  in Merge.kif

```
(=>
   (parent ?CHILD ?PARENT)
   (before (BeginFn (WhenFn ?PARENT)) (BeginFn (WhenFn ?CHILD))))
```

But I also found the definition of `older` and we could use it:

```
(=> (parent ?CHILD ?PARENT)
    (older ?PARENT ?CHILD))
```

Does it make sense to keep both? To remove the first one? To not add the new one for some reason?

**Comment by arademaker** [comment]
Milo? But `parent` was defined in `Merge.kif` not in the `Mid-level-ontology.kif`

**Comment by apease** [comment]
but &%older is defined in MILO

**Comment by vcvpaiva** [comment]
hmm, children are only biological children?
Because there are plenty of cases of stepmothers being younger than their
step-offspring...
Valeria

**Comment by arademaker** [comment]
Good point. But in that case the other axiom 

```
(=>
    (parent ?CHILD ?PARENT)
    (before (BeginFn (WhenFn ?PARENT)) (BeginFn (WhenFn ?CHILD))))
 ```

Need also to be removed

**Comment by apease** [comment]
please look at the definition of parent - https://sigma.ontologyportal.org:8443/sigma/Browse.jsp?kb=SUMO&lang=EnglishLanguage&flang=SUO-KIF&term=parent
It specifies biological parents and does not include cases like step-parent.
