### ISSUE TITLE
Move "conventionalShortName" definition to Mid-level-ontology.kif?

### ISSUE THREAD

**Issue by jefft0** [ontologyportal/sumo#31]
This is a low priority question. Should Mid-level-ontology.kif be self contained (with the help of Merge.kif)? I ask because it uses conventionalShortName:
(conventionalShortName "H" Hydrogen)
https://github.com/ontologyportal/sumo/blob/master/Mid-level-ontology.kif#L24379

When I load Mid-level-ontology.kif, I get several "conventionalShortName does not have an arity defined" warnings because the definition of conventionalShortName is in Government.kif:
https://github.com/ontologyportal/sumo/blob/master/Government.kif#L69

Should it be moved to Mid-level-ontology.kif?

**Comment by apease** [comment]
Hi Jeff
Yes ideally the ontologies shouldn't have mutual dependencies so this would be a good change to make.  The sigma diagnostics page will show a complete list of dependencies between files

Many thanks!
Adam

**Comment by jefft0** [comment]
See https://github.com/ontologyportal/sumo/pull/32 .
