### ISSUE TITLE
improve the wordnet mappings for SkilledOccupation

### ISSUE THREAD

**Issue by arademaker** [ontologyportal/sumo#4]
Some of them can be used in the wordnet mapping:

```
$ grep -c SkilledOccupation *.kif | awk -F ":" ' $2 > 0 { print }'
Biography.kif:8
Dining.kif:1
FinancialOntology.kif:2
Mid-level-ontology.kif:26
Military.kif:1
Sports.kif:3
domainEnglishFormat.kif:1
```

Related with #3 as suggested by @vcvpaiva. See initial changes in a2a5b9d.

**Comment by apease** [comment]
ontology contents were updated although a comprehensive review of professions is needed, closing issue for now
