### ISSUE TITLE
A complete story or fable in KIF

### ISSUE THREAD

**Issue by logicmoo** [ontologyportal/sumo#40]
It would be nice to have a complete story or fable translated to KIF In the examples.

**Comment by apease** [comment]
Hi Doug
Check out my sumo stories paper at adampease.org/professional . It might have what you're looking for
Cua, J., Manurung, R., Ong, E., and Pease, A., (2010). Representing Story Plans in SUMO, Proceedings of the NAACL HLT 2010 Second Workshop on Computational Approaches to Linguistic Creativity, Los Angeles, CA, June 5, 2010.

Adam

**Comment by apease** [comment]
answered question, no action item, closing issue

**Comment by arademaker** [comment]
Hi @apease , the link in your homepage is broken.  The right link is:

https://aclweb.org/anthology/papers/W/W10/W10-0306/

**Comment by apease** [comment]
thanks, fixed
