### ISSUE TITLE
duplicate statement in domainEnglishFormat.kif

### ISSUE THREAD

**Issue by ArtificialMarty** [ontologyportal/sumo#47]
sumo-2017-01-13/domainEnglishFormat.kif:
p: sumo-2017-01-13/domainEnglishFormat.kif:8675.1-8675.41: lexical duplicate input no de:
(termFormat EnglishLanguage Skin "skin")
p: sumo-2017-01-13/domainEnglishFormat.kif:1100.1-1100.41: <-- original sentence is h ere.

**Comment by ArtificialMarty** [comment]
Oops.  Line numbers cited are 1 less than they should be (0-origin in the lexer).  Sigh.

**Comment by msvarny** [comment]
This is corrected in the Biography.kif branch and will be merged into master soon.
