### ISSUE TITLE
duplicate statements in WordAirports.kif

### ISSUE THREAD

**Issue by ArtificialMarty** [ontologyportal/sumo#49]
[WorldAirports.txt](https://github.com/ontologyportal/sumo/files/733139/WorldAirports.txt)

**Comment by ArtificialMarty** [comment]
Oops.  Line numbers cited are 1 less than they should be (0-origin in the lexer).  Sigh.

**Comment by ArtificialMarty** [comment]
Updated list for commit bb8a4d1:

sumo-2017-01-29-bb8a4d1/WorldAirports.kif:
p: sumo-2017-01-29-bb8a4d1/WorldAirports.kif:287.1-287.45: lexical duplicate input node:
(located IncirlikAirBaseAdanaAirport Turkey)
p: sumo-2017-01-29-bb8a4d1/WorldAirports.kif:280.1-280.45: <-- original sentence is here.
p: sumo-2017-01-29-bb8a4d1/WorldAirports.kif:574.1-574.49: lexical duplicate input node:
(located ArdmoreMunicipalOKAirport UnitedStates)
p: sumo-2017-01-29-bb8a4d1/WorldAirports.kif:319.1-319.49: <-- original sentence is here.
p: sumo-2017-01-29-bb8a4d1/WorldAirports.kif:25381.1-25381.36: lexical duplicate input node:
(instance KoelnKolnAirport Airport)
p: sumo-2017-01-29-bb8a4d1/WorldAirports.kif:4988.1-4988.36: <-- original sentence is here.
p: sumo-2017-01-29-bb8a4d1/WorldAirports.kif:32017.1-32017.39: lexical duplicate input node:
(instance PuertoLaCruzAirport Airport)
p: sumo-2017-01-29-bb8a4d1/WorldAirports.kif:23357.1-23357.39: <-- original sentence is here.
p: sumo-2017-01-29-bb8a4d1/WorldAirports.kif:32019.1-32019.40: lexical duplicate input node:
(located PuertoLaCruzAirport Venezuela)
p: sumo-2017-01-29-bb8a4d1/WorldAirports.kif:23359.1-23359.40: <-- original sentence is here.

**Comment by msvarny** [comment]
Thanks for the report. Just want to note that this issue is mentioned also in issue #26.

**Comment by ArtificialMarty** [comment]
Hadn't checked on this in a while, but it has been fixed.
