### ISSUE TITLE
mapping: elephant

### ISSUE THREAD

**Issue by vcvpaiva** [ontologyportal/sumo#77]
I cannot see a reason for this to be a subsuming mapping
Noun Synset: 102503517
SUMO Mappings: Elephant (subsuming mapping)

There is only one synset about elephants (there is another one about the symbol of the Republican party and one about a plant which has elephant in its name).

**Comment by arademaker** [comment]
It looks like commit 8189a2b6908ca99fea7cb347ebcde09febf8880f solved it.
