### ISSUE TITLE
Representing SUMO's knowledge in statically typed languages

### ISSUE THREAD

**Issue by nordlow** [ontologyportal/sumo#87]
Is there any documentation that briefly highlights guidlines/recommendations on representing SUMO knowledge expressions (in the .kif-files) in (statically) typed languages. I'm thinking mostly of the facts that

- relations in SUMO can refer to both data and other relations
- but data (atoms) only refer to relations

I'm asking because I'm currently adding support for representing SUMO-expressions in my knowledge graph written in the D programming language. And my current proposed implementation is semi-statically typed as follows:

- `Edge`: contains references (index), where each reference can be either a `Edge` and or a `Node`
- `Node`: contains references to the `Edge`s that refer to it.

Is there a foramal name for this kind of graph? AFAICT, according to https://en.wikipedia.org/wiki/Hypergraph this is more advanced than a hypergraph, as those hypergraphs doesn't included relations between relations.

A very primitive practical example of this is how to define subKind-superKind-relations between WordNet's synonym sets.

**Comment by apease** [comment]
Hi Per,
   In the sigmakee project on ontologyportal look at 
com.articulate.sigma.KButilities and there is a method 
createSemanticNetwork() that should be of help.

all the best,
Adam

**Comment by nordlow** [comment]
Cannot find any symbol named `createSemanticNetwork` anywhere in sigmakee repo.

**Comment by apease** [comment]
sorry my typo - generateSemanticNetwork(), starting line 204 of 
https://github.com/ontologyportal/sigmakee/blob/master/src/java/com/articulate/sigma/KButilities.java

**Comment by apease** [comment]
answered question, no action item, closing issue
