### ISSUE TITLE
Human language mapping alternatives

### ISSUE THREAD

**Issue by nordlow** [ontologyportal/sumo#88]
Have you considered extending the language mappings to contain alternative human language expressions such as

 ```Lisp
(format EnglishLanguage attribute (or "%2 is %n an &%attribute of %1"
                                       "%1 has %n the &%attribute %2"))
```

?

I'm aware of, that it should be `hasn't` instead of `has not` :)

**Comment by apease** [comment]
Hi Per,

   We could have alternatives but then the question would be how to 
select among them in language generation.  With the current approach, we 
need one best (or least bad) option.  Another approach would be to 
refine the very rudimentary scheme for language generation itself, so we 
could have a more expressive language of options for the templates.  One 
such improvement I have planned is in making better use of prepositional 
phrases in action expressions.  For example


(and

   (instance ?S SittingDown)

   (agent ?S John)

   (destination ?S JohnsEasyChair))


Right now we get something like "There is a sitting down and John is 
agent of the sitting down and the destination of the sitting down is 
JohnsEasyChair".  Instead, we could have a not-too-complicated 
deterministic algorithm to generate "John is sitting down on 
JohnsEasyChair."


all the best,

Adam

**Comment by apease** [comment]
answered questions, no action item, closing issue
