### ISSUE TITLE
No formal generic participant

### ISSUE THREAD

**Issue by nordlow** [ontologyportal/sumo#91]
Is there a reason why SUMO currently doesn't contain a generic definition of `participant` in constrast to the only having `contestParticipant`?

**Comment by apease** [comment]
Hi Per,

   I think you'd need to explain further what you mean here, but I'm 
guessing that what you're looking for in SUMO is &%patient or possibly 
&%involvedInEvent, which is the most general relation specifying some 
role in a Process

all the best,

Adam

**Comment by nordlow** [comment]
Thanks!
