### ISSUE TITLE
Single biological father and mother

### ISSUE THREAD

**Issue by nordlow** [ontologyportal/sumo#93]
How does SUMO express the fact that a person X can only have a single biological mother or father, which entails exactly two biological parents.

Update: Ahh, this is what `SingleValuedRelation` is for, right?

If so, can you please explain what `TotalValuedRelation` mean? I find the doc in `Merge.kif` hard to grasp :)

**Comment by apease** [comment]
father is a SingleValuedRelation http://sigma.ontologyportal.org:8080/sigma/Browse.jsp?lang=EnglishLanguage&flang=SUO-KIF&kb=SUMO&term=SingleValuedRelation

Sent from my iPhone
http://www.ontologyportal.org

On Aug 18, 2017, at 12:45 PM, Per Nordlöw <notifications@github.com<mailto:notifications@github.com>> wrote:


How does SUMO express the fact that a person X can only have a single biological mother or father, which entails exactly two biological parents.

**Comment by nordlow** [comment]
Is there some documentation that describes the ideas behind `SingleValuedRelation`s and `TotalValuedRelation`s?

**Comment by apease** [comment]
Hi Per,

   The best documentation on any individual term is just its browser page

http://sigma.ontologyportal.org:8080/sigma/Browse.jsp?kb=SUMO&lang=EnglishLanguage&flang=SUO-KIF&term=SingleValuedRelation
http://sigma.ontologyportal.org:8080/sigma/Browse.jsp?kb=SUMO&lang=EnglishLanguage&flang=SUO-KIF&term=TotalValuedRelation

(documentation TotalValuedRelation EnglishLanguage "A Relation is a 
TotalValuedRelation just in case there exists an assignment for the last 
argument position of the Relation given any assignment of values to 
every argument position except the last one. Note that declaring a 
Relation to be both a TotalValuedRelation and a SingleValuedRelation 
means that it is a total function.")

(documentation SingleValuedRelation EnglishLanguage "A Relation is a 
SingleValuedRelation just in case an assignment of values to every 
argument position except the last one determines at most one assignment 
for the last argument position. Note that not all SingleValuedRelations 
are TotalValuedRelations.")

Do those documentation statements address your question?

all the best,
Adam

**Comment by nordlow** [comment]
Ok, thanks.

BTW:

Why is son and daughter defined as

```
(subrelation son parent)
(subrelation daugther parent)
```

with their arguments reversed, like

```
(hasSon ?PARENT ?CHILD)
(hasDaughter ?PARENT ?CHILD)
```

?

**Comment by apease** [comment]
Hi Per,

   I'm not clear on the concern here.  There is no relation &%hasSon in 
SUMO.  &%son, &%daughter and &%parent are all consistent in having the 
child as the first argument. Could you explain further?


all the best,

Adam

**Comment by apease** [comment]
answered questions, no action item, closing issue
